version: "3.9"

services:
  common-config-template:
    volumes:
      - shared-empty-dir:/tmp/shared-empty-dir
    networks:
      - macvlan-net
    labels:
      ENV: "test"
      PLATFORM: "compose"
    secrets:
      - datadog-api-key
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      placement:
        constraints:
          - node.role == worker
